CC = g++

bench: 
	$(CC) benchmark.cpp -o benchmark.exe
	./benchmark.exe
algos: 
	$(CC) algos_main.cpp -o algos.exe
	./algos.exe
hybrid: 
	$(CC) hybrid_main.cpp -o hybrid.exe
	./hybrid.exe
clean:
	-rm *.exe
